### ISSUE TITLE
Question: How to change redis port?

### ISSUE THREAD

**Issue by Epigene** [dokku/dokku-redis#42]
How do I specify a custom port for redis to run on?

I have tried using the REDIS_CUSTOM_ENV variable to no avail.

```
> export REDIS_CUSTOM_ENV="PORT=6392"
> dokku redis:create myapp
=====> Redis container created: myapp
       DSN: redis://dokku-redis-myapp:6379/0
```

I am trying to mirror redis access locally via `redis://localhost:6392`. I guess I'd be fine with changes in the host part to `redis://dokku-redis-myapp:6392`

**Comment by josegonzalez** [comment]
Your local mirror's port has nothing to do with this service's port.

**Comment by Epigene** [comment]
There has been a misunderstanding.

I need to load a redis instance for resque. I normally achieve this with two pieces of code:

1. a yaml file of redis locations for each environment

```yml
# in /config/redis.yml
development:
  redis: redis://localhost:6390/
test:
  redis: redis://localhost:6391/
staging:
  redis: redis://dokku-redis-myapp:6379/0
```

2. an initializer that reads the yml file and sets up a redis instance for resque

```ruby
# in /config/initializers/resque.rb
config = YAML::load(File.open("#{Rails.root}/config/redis.yml"))[Rails.env]
uri = URI.parse(config["redis"])

Resque.redis = Redis.new(host: uri.host, port: uri.port, password: uri.password, thread_safe: true)
```

So my question is, how can I configure the host/port of redis I link to myapp, so that I can use

```yml
staging:
  redis: redis://some-host:6392/
```

__NB__, I am not yet sure even the default 'redis://dokku-redis-myapp:6379/0' works.
